ALTER TABLE menu_items
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE menu_items
ADD COLUMN IF NOT EXISTS is_bestseller BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE menu_items
ADD COLUMN IF NOT EXISTS is_top10 BOOLEAN NOT NULL DEFAULT FALSE;